services:
  frontend:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.frontend
      args:
        VITE_PIN_CODE: ${VITE_PIN_CODE}
        VITE_VERIFICATION_COOKIE_NAME: ${VITE_VERIFICATION_COOKIE_NAME}
        VITE_VERIFICATION_TIMEOUT_MS: ${VITE_VERIFICATION_TIMEOUT_MS}
    ports:
      - "80:80"
      - "443:443"  # <-- ADICIONE ESTA LINHA
    networks:
      - default
      - rede-global-proxy
    env_file:
      - .env
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      # ADICIONE O BLOCO ABAIXO PARA OS CERTIFICADOS
      - /etc/letsencrypt:/etc/letsencrypt:ro
    depends_on:
      - backend
    restart: unless-stopped
    container_name: financial-app-frontend

  backend:
    build:
      context: ../../
      dockerfile: infra/docker/Dockerfile.backend
    networks:
      - default
      - rede-global-proxy
    env_file:
      - .env
    environment:
      - NODE_ENV=production
    restart: unless-stopped
    container_name: financial-app-backend
  
networks:
  default:
    driver: bridge
  rede-global-proxy:
    name: rede-global-proxy
    driver: bridge
