apiVersion: v1
kind: Secret
metadata:
  name: vibecodia-backend-secret
type: Opaque
stringData:
  MONGO_ATLAS_URI: "mongodb+srv://<username>:<password>@<cluster-name>.mongodb.net/<database-name>?retryWrites=true&w=majority"
  VAPID_PUBLIC_KEY: "replace-with-vapid-public-key"
  VAPID_PRIVATE_KEY: "replace-with-vapid-private-key"
