apiVersion: v1
kind: ServiceAccount
metadata:
  name: financial-app-sa
  namespace: financial
  labels:
    app: financial-app
    managed-by: kustomize
    project: devops-lab
    challenge: "11"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: financial-app-role
  namespace: financial
  labels:
    app: financial-app
    managed-by: kustomize
    project: devops-lab
    challenge: "11"
rules:
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: [""]
  resources: ["secrets"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: financial-app-rolebinding
  namespace: financial
  labels:
    app: financial-app
    managed-by: kustomize
    project: devops-lab
    challenge: "11"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: financial-app-role
subjects:
- kind: ServiceAccount
  name: financial-app-sa
  namespace: financial
