apiVersion: v1
kind: ServiceAccount
metadata:
  name: financial-deployer
  namespace: financial
  labels:
    app: financial-app
    managed-by: kustomize
    project: devops-lab
    challenge: "11"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: financial-deployer-role
  namespace: financial
  labels:
    app: financial-app
    managed-by: kustomize
    project: devops-lab
    challenge: "11"
rules:
# kubectl set image — faz patch no Deployment
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "patch", "update"]
# kubectl rollout status — observa os pods subindo
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: financial-deployer-rolebinding
  namespace: financial
  labels:
    app: financial-app
    managed-by: kustomize
    project: devops-lab
    challenge: "11"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: financial-deployer-role
subjects:
- kind: ServiceAccount
  name: financial-deployer
  namespace: financial
