import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Push Notification Logic
self.addEventListener('push', (event) => {
  if (!event.data) return;

  try {
    const data = event.data.json();
    const { title, body, tag, icon, data: customData } = data;

    const options = {
      body,
      tag, // Important for grouping/overwriting
      icon: icon || '/favicon.svg',
      badge: '/favicon.svg',
      renotify: true, // Renotify when using same tag
      data: customData || {},
      vibrate: [100, 50, 100],
      actions: [
        { action: 'open', title: 'Ver Contas' }
      ]
    };

    event.waitUntil(
      self.registration.showNotification(title, options)
    );
  } catch (err) {
    console.error('Error handling push event:', err);
  }
});

// Notification Click Logic
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if there is already a window open with this URL
      for (let client of windowClients) {
        if (client.url.includes(urlToOpen) && 'focus' in client) {
          return client.focus();
        }
      }
      // If no window is open or it's a different URL, open a new one or navigate existing
      if (windowClients.length > 0) {
        return windowClients[0].navigate(urlToOpen).then(client => client?.focus());
      }
      if (clients.openWindow) {
        return clients.openWindow(urlToOpen);
      }
    })
  );
});
