/* eslint-disable no-undef */
import { precacheAndRoute } from 'workbox-precaching';

// Precache all assets generated by Vite
precacheAndRoute(self.__WB_MANIFEST);

// Force update of the service worker
self.addEventListener('install', () => {
  self.skipWaiting();
});

self.addEventListener('activate', (event) => {
  event.waitUntil(clients.claim());
});

// Push Notification Logic
self.addEventListener('push', (event) => {
  let data = {
    title: 'Vibecodia Finances',
    body: 'Você tem novas atualizações.',
    tag: 'default-notification',
    data: { url: '/' }
  };

  if (event.data) {
    try {
      data = event.data.json();
    } catch (err) {
      console.error('Error parsing push data:', err);
      // If not JSON, try text
      data.body = event.data.text();
    }
  }

  const options = {
    body: data.body,
    tag: data.tag || 'default-notification',
    icon: data.icon || '/favicon.svg',
    badge: '/favicon.svg',
    renotify: true,
    data: data.data || { url: '/' },
    vibrate: [100, 50, 100],
    actions: [
      { action: 'open', title: 'Ver Contas' }
    ]
  };

  event.waitUntil(
    self.registration.showNotification(data.title || 'Vibecodia Finances', options)
  );
});

// Notification Click Logic
self.addEventListener('notificationclick', (event) => {
  event.notification.close();

  const urlToOpen = event.notification.data?.url || '/';

  event.waitUntil(
    clients.matchAll({ type: 'window', includeUncontrolled: true }).then((windowClients) => {
      // Check if there is already a window open with this URL
      for (let client of windowClients) {
        if (client.url.includes(urlToOpen) && 'focus' in client) {
          return client.focus();
        }
      }
      // If no window is open or it's a different URL, open a new one or navigate existing
      if (windowClients.length > 0) {
        return windowClients[0].navigate(urlToOpen).then(client => client?.focus());
      }
      if (clients.openWindow) {
        return clients.openWindow(urlToOpen);
      }
    })
  );
});
