name: CI WIP
on:
  push:
    branches:
      - 'wip/*'

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - env:
        MY_PAT: ${{ secrets.MY_PAT }}
        with:
          node-version: 20
          cache: 'npm'
      - run: npm ci
      - run: npm run lint
      - run: npm run build
      - run: npm run release:dry-run